server:
  addr: 127.0.0.1:8087
  name: "ms-api"
zap:
  debugFileName: "D:\\go\\project\\project_ws\\logs\\debug\\project-debug.log"
  infoFileName: "D:\\go\\project\\project_ws\\logs\\info\\project-info.log"
  warnFileName: "D:\\go\\project\\project_ws\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3

