// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: login_service.proto

package login

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptchaMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaMessage) Reset() {
	*x = CaptchaMessage{}
	mi := &file_login_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaMessage) ProtoMessage() {}

func (x *CaptchaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaMessage.ProtoReflect.Descriptor instead.
func (*CaptchaMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{0}
}

func (x *CaptchaMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type CaptchaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaResponse) Reset() {
	*x = CaptchaResponse{}
	mi := &file_login_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaResponse) ProtoMessage() {}

func (x *CaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaResponse.ProtoReflect.Descriptor instead.
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,4,opt,name=captcha,proto3" json:"captcha,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	mi := &file_login_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterMessage) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *RegisterMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_login_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{3}
}

type LoginMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_login_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginMessage) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Member           *MemberMessage         `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	OrganizationList []*OrganizationMessage `protobuf:"bytes,2,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	TokenList        *TokenMessage          `protobuf:"bytes,3,opt,name=tokenList,proto3" json:"tokenList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_login_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetMember() *MemberMessage {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *LoginResponse) GetOrganizationList() []*OrganizationMessage {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

func (x *LoginResponse) GetTokenList() *TokenMessage {
	if x != nil {
		return x.TokenList
	}
	return nil
}

type MemberMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile           string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Realname         string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	Account          string                 `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Status           int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime    string                 `protobuf:"bytes,7,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	Address          string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province         int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City             int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area             int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Email            string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	Code             string                 `protobuf:"bytes,13,opt,name=code,proto3" json:"code,omitempty"`
	CreateTime       string                 `protobuf:"bytes,14,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OrganizationCode string                 `protobuf:"bytes,15,opt,name=organizationCode,proto3" json:"organizationCode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberMessage) Reset() {
	*x = MemberMessage{}
	mi := &file_login_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMessage) ProtoMessage() {}

func (x *MemberMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMessage.ProtoReflect.Descriptor instead.
func (*MemberMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{6}
}

func (x *MemberMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberMessage) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *MemberMessage) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *MemberMessage) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MemberMessage) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MemberMessage) GetLastLoginTime() string {
	if x != nil {
		return x.LastLoginTime
	}
	return ""
}

func (x *MemberMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MemberMessage) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *MemberMessage) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *MemberMessage) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *MemberMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *MemberMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MemberMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *MemberMessage) GetOrganizationCode() string {
	if x != nil {
		return x.OrganizationCode
	}
	return ""
}

type OrganizationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MemberId      int64                  `protobuf:"varint,5,opt,name=memberId,proto3" json:"memberId,omitempty"`
	CreateTime    string                 `protobuf:"bytes,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Personal      int32                  `protobuf:"varint,7,opt,name=personal,proto3" json:"personal,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Province      int32                  `protobuf:"varint,9,opt,name=province,proto3" json:"province,omitempty"`
	City          int32                  `protobuf:"varint,10,opt,name=city,proto3" json:"city,omitempty"`
	Area          int32                  `protobuf:"varint,11,opt,name=area,proto3" json:"area,omitempty"`
	Code          string                 `protobuf:"bytes,12,opt,name=code,proto3" json:"code,omitempty"`
	OwnerCode     string                 `protobuf:"bytes,13,opt,name=ownerCode,proto3" json:"ownerCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationMessage) Reset() {
	*x = OrganizationMessage{}
	mi := &file_login_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationMessage) ProtoMessage() {}

func (x *OrganizationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationMessage.ProtoReflect.Descriptor instead.
func (*OrganizationMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{7}
}

func (x *OrganizationMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrganizationMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationMessage) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *OrganizationMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationMessage) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *OrganizationMessage) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *OrganizationMessage) GetPersonal() int32 {
	if x != nil {
		return x.Personal
	}
	return 0
}

func (x *OrganizationMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *OrganizationMessage) GetProvince() int32 {
	if x != nil {
		return x.Province
	}
	return 0
}

func (x *OrganizationMessage) GetCity() int32 {
	if x != nil {
		return x.City
	}
	return 0
}

func (x *OrganizationMessage) GetArea() int32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *OrganizationMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OrganizationMessage) GetOwnerCode() string {
	if x != nil {
		return x.OwnerCode
	}
	return ""
}

type TokenMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken   string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	TokenType      string                 `protobuf:"bytes,3,opt,name=tokenType,proto3" json:"tokenType,omitempty"`
	AccessTokenExp int64                  `protobuf:"varint,4,opt,name=accessTokenExp,proto3" json:"accessTokenExp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenMessage) Reset() {
	*x = TokenMessage{}
	mi := &file_login_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMessage) ProtoMessage() {}

func (x *TokenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMessage.ProtoReflect.Descriptor instead.
func (*TokenMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{8}
}

func (x *TokenMessage) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenMessage) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenMessage) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenMessage) GetAccessTokenExp() int64 {
	if x != nil {
		return x.AccessTokenExp
	}
	return 0
}

type UserMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemId         int64                  `protobuf:"varint,1,opt,name=memId,proto3" json:"memId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_login_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{9}
}

func (x *UserMessage) GetMemId() int64 {
	if x != nil {
		return x.MemId
	}
	return 0
}

type OrgListResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationList []*OrganizationMessage `protobuf:"bytes,1,rep,name=organizationList,proto3" json:"organizationList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OrgListResponse) Reset() {
	*x = OrgListResponse{}
	mi := &file_login_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgListResponse) ProtoMessage() {}

func (x *OrgListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgListResponse.ProtoReflect.Descriptor instead.
func (*OrgListResponse) Descriptor() ([]byte, []int) {
	return file_login_service_proto_rawDescGZIP(), []int{10}
}

func (x *OrgListResponse) GetOrganizationList() []*OrganizationMessage {
	if x != nil {
		return x.OrganizationList
	}
	return nil
}

var File_login_service_proto protoreflect.FileDescriptor

const file_login_service_proto_rawDesc = "" +
	"\n" +
	"\x13login_service.proto\x12\x10login.service.v1\"(\n" +
	"\x0eCaptchaMessage\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\"%\n" +
	"\x0fCaptchaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x89\x01\n" +
	"\x0fRegisterMessage\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\acaptcha\x18\x04 \x01(\tR\acaptcha\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"\x12\n" +
	"\x10RegisterResponse\"Z\n" +
	"\fLoginMessage\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xd9\x01\n" +
	"\rLoginResponse\x127\n" +
	"\x06member\x18\x01 \x01(\v2\x1f.login.service.v1.MemberMessageR\x06member\x12Q\n" +
	"\x10organizationList\x18\x02 \x03(\v2%.login.service.v1.OrganizationMessageR\x10organizationList\x12<\n" +
	"\ttokenList\x18\x03 \x01(\v2\x1e.login.service.v1.TokenMessageR\ttokenList\"\x93\x03\n" +
	"\rMemberMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x18\n" +
	"\aaccount\x18\x05 \x01(\tR\aaccount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12$\n" +
	"\rlastLoginTime\x18\a \x01(\tR\rlastLoginTime\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\r \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"createTime\x18\x0e \x01(\tR\n" +
	"createTime\x12*\n" +
	"\x10organizationCode\x18\x0f \x01(\tR\x10organizationCode\"\xdb\x02\n" +
	"\x13OrganizationMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmemberId\x18\x05 \x01(\x03R\bmemberId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1a\n" +
	"\bpersonal\x18\a \x01(\x05R\bpersonal\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\t \x01(\x05R\bprovince\x12\x12\n" +
	"\x04city\x18\n" +
	" \x01(\x05R\x04city\x12\x12\n" +
	"\x04area\x18\v \x01(\x05R\x04area\x12\x12\n" +
	"\x04code\x18\f \x01(\tR\x04code\x12\x1c\n" +
	"\townerCode\x18\r \x01(\tR\townerCode\"\x9a\x01\n" +
	"\fTokenMessage\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\ttokenType\x18\x03 \x01(\tR\ttokenType\x12&\n" +
	"\x0eaccessTokenExp\x18\x04 \x01(\x03R\x0eaccessTokenExp\"#\n" +
	"\vUserMessage\x12\x14\n" +
	"\x05memId\x18\x01 \x01(\x03R\x05memId\"d\n" +
	"\x0fOrgListResponse\x12Q\n" +
	"\x10organizationList\x18\x01 \x03(\v2%.login.service.v1.OrganizationMessageR\x10organizationList2\xa7\x03\n" +
	"\fLoginService\x12S\n" +
	"\n" +
	"GetCaptcha\x12 .login.service.v1.CaptchaMessage\x1a!.login.service.v1.CaptchaResponse\"\x00\x12S\n" +
	"\bRegister\x12!.login.service.v1.RegisterMessage\x1a\".login.service.v1.RegisterResponse\"\x00\x12J\n" +
	"\x05Login\x12\x1e.login.service.v1.LoginMessage\x1a\x1f.login.service.v1.LoginResponse\"\x00\x12P\n" +
	"\vTokenVerify\x12\x1e.login.service.v1.LoginMessage\x1a\x1f.login.service.v1.LoginResponse\"\x00\x12O\n" +
	"\tMyOrgList\x12\x1d.login.service.v1.UserMessage\x1a!.login.service.v1.OrgListResponse\"\x00B&Z$ms-user/pkg/service/login_service.v1b\x06proto3"

var (
	file_login_service_proto_rawDescOnce sync.Once
	file_login_service_proto_rawDescData []byte
)

func file_login_service_proto_rawDescGZIP() []byte {
	file_login_service_proto_rawDescOnce.Do(func() {
		file_login_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_service_proto_rawDesc), len(file_login_service_proto_rawDesc)))
	})
	return file_login_service_proto_rawDescData
}

var file_login_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_login_service_proto_goTypes = []any{
	(*CaptchaMessage)(nil),      // 0: login.service.v1.CaptchaMessage
	(*CaptchaResponse)(nil),     // 1: login.service.v1.CaptchaResponse
	(*RegisterMessage)(nil),     // 2: login.service.v1.RegisterMessage
	(*RegisterResponse)(nil),    // 3: login.service.v1.RegisterResponse
	(*LoginMessage)(nil),        // 4: login.service.v1.LoginMessage
	(*LoginResponse)(nil),       // 5: login.service.v1.LoginResponse
	(*MemberMessage)(nil),       // 6: login.service.v1.MemberMessage
	(*OrganizationMessage)(nil), // 7: login.service.v1.OrganizationMessage
	(*TokenMessage)(nil),        // 8: login.service.v1.TokenMessage
	(*UserMessage)(nil),         // 9: login.service.v1.UserMessage
	(*OrgListResponse)(nil),     // 10: login.service.v1.OrgListResponse
}
var file_login_service_proto_depIdxs = []int32{
	6,  // 0: login.service.v1.LoginResponse.member:type_name -> login.service.v1.MemberMessage
	7,  // 1: login.service.v1.LoginResponse.organizationList:type_name -> login.service.v1.OrganizationMessage
	8,  // 2: login.service.v1.LoginResponse.tokenList:type_name -> login.service.v1.TokenMessage
	7,  // 3: login.service.v1.OrgListResponse.organizationList:type_name -> login.service.v1.OrganizationMessage
	0,  // 4: login.service.v1.LoginService.GetCaptcha:input_type -> login.service.v1.CaptchaMessage
	2,  // 5: login.service.v1.LoginService.Register:input_type -> login.service.v1.RegisterMessage
	4,  // 6: login.service.v1.LoginService.Login:input_type -> login.service.v1.LoginMessage
	4,  // 7: login.service.v1.LoginService.TokenVerify:input_type -> login.service.v1.LoginMessage
	9,  // 8: login.service.v1.LoginService.MyOrgList:input_type -> login.service.v1.UserMessage
	1,  // 9: login.service.v1.LoginService.GetCaptcha:output_type -> login.service.v1.CaptchaResponse
	3,  // 10: login.service.v1.LoginService.Register:output_type -> login.service.v1.RegisterResponse
	5,  // 11: login.service.v1.LoginService.Login:output_type -> login.service.v1.LoginResponse
	5,  // 12: login.service.v1.LoginService.TokenVerify:output_type -> login.service.v1.LoginResponse
	10, // 13: login.service.v1.LoginService.MyOrgList:output_type -> login.service.v1.OrgListResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_login_service_proto_init() }
func file_login_service_proto_init() {
	if File_login_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_service_proto_rawDesc), len(file_login_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_login_service_proto_goTypes,
		DependencyIndexes: file_login_service_proto_depIdxs,
		MessageInfos:      file_login_service_proto_msgTypes,
	}.Build()
	File_login_service_proto = out.File
	file_login_service_proto_goTypes = nil
	file_login_service_proto_depIdxs = nil
}
